#!/bin/sh

wav2slin()
{
	sox "$1" -t raw -r 8000 -c 1 -e signed-integer "$2"
}

case "$1" in
	-d)
		for i in `find $2 -type f -name \*.wav`; do
			out="`dirname $i`/`basename $i .wav`.slin"
			if [ ! -f $out ]; then
				wav2slin $i $out
			fi
		done
		;;
	*)
		wav2slin "$1" "$2"
		;;
esac
